### ISSUE TITLE
update-alternatives: error: no alternatives for mozilla-javaplugin.so

### ISSUE THREAD

**Issue by shengrongjin** [martinruenz/maskfusion#1]
Hello ,Firstly , thank you for your contribution about Maskfusion's method and code !  When I build the environment of Maskfusion as the build.sh described and execute the command: sudo update-java-alternatives -s java-1.8.0-openjdk-amd64, I had meet a error that It is update-alternatives: error: no alternatives for mozilla-javaplugin.so , I can't  solve this error . Can you help me ? Thank you for your help sincerely !

**Comment by shengrongjin** [comment]
I had solved this problem .   Thank you .

**Comment by Su-deep** [comment]
solution: sudo apt-get install icedtea-8-plugin

**Comment by sbabubo9** [comment]
: Package 'icedtea-8-plugin' has no installation candidate

**Comment by archf** [comment]
This I did try without success `sudo apt-get install icedtea-8-plugin`? How did you do it? 
Using Ubuntu 18.04.2 LTS

**Comment by myfingerhurt** [comment]
Not sure it works or not try this.
Ubuntu20.04 LTS
sudo apt-get install icedtea-netx
