### ISSUE TITLE
about toml

### ISSUE THREAD

**Issue by robustlucy** [martinruenz/maskfusion#17]
Hi, I tried the latest version of maskfusion and got this message:
[ 77%] Built target MaskFusionTools
Scanning dependencies of target MaskFusion
[ 79%] Building CXX object GUI/CMakeFiles/MaskFusion.dir/Main.cpp.o
[ 81%] Building CXX object GUI/CMakeFiles/MaskFusion.dir/MainController.cpp.o
/home/titan/maskfusion/GUI/MainController.cpp: In constructor ‘MainController::MainController(int, char**)’:
/home/titan/maskfusion/GUI/MainController.cpp:277:45: error: conversion from ‘toml::basic_value<toml::discard_comments, std::unordered_map, std::vector>’ to non-scalar type ‘toml::table {aka std::unordered_map<std::__cxx11::basic_string<char>, toml::basic_value<toml::discard_comments, std::unordered_map, std::vector> >}’ requested
         toml::table tomlConfig = toml::parse("config.toml");
                                             ^
/home/titan/maskfusion/GUI/MainController.cpp:278:45: error: ‘Table’ is not a member of ‘toml’
         const auto tomlMaskRCNN = toml::get<toml::Table>(tomlConfig.at("MaskRCNN"));
                                             ^
/home/titan/maskfusion/GUI/MainController.cpp:278:45: error: ‘Table’ is not a member of ‘toml’
/home/titan/maskfusion/GUI/MainController.cpp:278:83: error: no matching function for call to ‘get(std::unordered_map<std::__cxx11::basic_string<char>, toml::basic_value<toml::discard_comments, std::unordered_map, std::vector> >::mapped_type&)’
         const auto tomlMaskRCNN = toml::get<toml::Table>(tomlConfig.at("MaskRCNN"));
                                                                                   ^
In file included from /home/titan/maskfusion/deps/toml11/toml.hpp:39:0,
                 from /home/titan/maskfusion/GUI/MainController.cpp:32:
/home/titan/maskfusion/deps/toml11/toml/get.hpp:19:1: note: candidate: template<class T, class C, template<class ...> class M, template<class ...> class V> toml::detail::enable_if_t<toml::detail::is_exact_toml_type<T, toml::basic_value<C, Tb, A> >::value, T>& toml::get(toml::basic_value<C, Tb, A>&)
 get(basic_value<C, M, V>& v)
 ^
/home/titan/maskfusion/deps/toml11/toml/get.hpp:19:1: note:   template argument deduction/substitution failed:
/home/titan/maskfusion/GUI/MainController.cpp:278:83: error: template argument 1 is invalid
         const auto tomlMaskRCNN = toml::get<toml::Table>(tomlConfig.at("MaskRCNN"));
                                                                                   ^
In file included from /home/titan/maskfusion/deps/toml11/toml.hpp:39:0,
                 from /home/titan/maskfusion/GUI/MainController.cpp:32:
/home/titan/maskfusion/deps/toml11/toml/get.hpp:27:1: note: candidate: template<class T, class C, template<class ...> class M, template<class ...> class V> toml::detail::enable_if_t<toml::detail::is_exact_toml_type<T, toml::basic_value<C, Tb, A> >::value, T>& toml::get(const toml::basic_value<C, Tb, A>&)
 get(const basic_value<C, M, V>& v)
 ^
/home/titan/maskfusion/deps/toml11/toml/get.hpp:27:1: note:   template argument deduction/substitution failed:
/home/titan/maskfusion/GUI/MainController.cpp:278:83: error: template argument 1 is invalid
         const auto tomlMaskRCNN = toml::get<toml::Table>(tomlConfig.at("MaskRCNN"));
                                                                                   ^
In file included from /home/titan/maskfusion/deps/toml11/toml.hpp:39:0,
                 from /home/titan/maskfusion/GUI/MainController.cpp:32:
/home/titan/maskfusion/deps/toml11/toml/get.hpp:35:1: note: candidate: template<class T, class C, template<class ...> class M, template<class ...> class V> toml::detail::enable_if_t<toml::detail::is_exact_toml_type<T, toml::basic_value<C, Tb, A> >::value, T>&& toml::get(toml::basic_value<C, Tb, A>&&)
 get(basic_value<C, M, V>&& v)
 ^
/home/titan/maskfusion/deps/toml11/toml/get.hpp:35:1: note:   template argument deduction/substitution failed:
/home/titan/maskfusion/GUI/MainController.cpp:278:83: error: template argument 1 is invalid
         const auto tomlMaskRCNN = toml::get<toml::Table>(tomlConfig.at("MaskRCNN"));
                                                                                   ^
In file included from /home/titan/maskfusion/deps/toml11/toml.hpp:39:0,
                 from /home/titan/maskfusion/GUI/MainController.cpp:32:
/home/titan/maskfusion/deps/toml11/toml/get.hpp:46:1: note: candidate: template<class T, class C, template<class ...> class M, template<class ...> class V> toml::detail::enable_if_t<std::is_same<T, toml::basic_value<C, Tb, A> >::value, T>& toml::get(toml::basic_value<C, Tb, A>&)
 get(basic_value<C, M, V>& v)
 ^
/home/titan/maskfusion/deps/toml11/toml/get.hpp:46:1: note:   template argument deduction/substitution failed:
/home/titan/maskfusion/GUI/MainController.cpp:278:83: error: template argument 1 is invalid
         const auto tomlMaskRCNN = toml::get<toml::Table>(tomlConfig.at("MaskRCNN"));
                                                                                   ^
In file included from /home/titan/maskfusion/deps/toml11/toml.hpp:39:0,
                 from /home/titan/maskfusion/GUI/MainController.cpp:32:
/home/titan/maskfusion/deps/toml11/toml/get.hpp:54:1: note: candidate: template<class T, class C, template<class ...> class M, template<class ...> class V> toml::detail::enable_if_t<std::is_same<T, toml::basic_value<C, Tb, A> >::value, T>& toml::get(const toml::basic_value<C, Tb, A>&)
 get(const basic_value<C, M, V>& v)
 ^
/home/titan/maskfusion/deps/toml11/toml/get.hpp:54:1: note:   template argument deduction/substitution failed:
/home/titan/maskfusion/GUI/MainController.cpp:278:83: error: template argument 1 is invalid
         const auto tomlMaskRCNN = toml::get<toml::Table>(tomlConfig.at("MaskRCNN"));
                                                                                   ^
In file included from /home/titan/maskfusion/deps/toml11/toml.hpp:39:0,
                 from /home/titan/maskfusion/GUI/MainController.cpp:32:
/home/titan/maskfusion/deps/toml11/toml/get.hpp:62:1: note: candidate: template<class T, class C, template<class ...> class M, template<class ...> class V> toml::detail::enable_if_t<std::is_same<T, toml::basic_value<C, Tb, A> >::value, T>&& toml::get(toml::basic_value<C, Tb, A>&&)
 get(basic_value<C, M, V>&& v)
 ^
/home/titan/maskfusion/deps/toml11/toml/get.hpp:62:1: note:   template argument deduction/substitution failed:
/home/titan/maskfusion/GUI/MainController.cpp:278:83: error: template argument 1 is invalid
         const auto tomlMaskRCNN = toml::get<toml::Table>(tomlConfig.at("MaskRCNN"));
                                                                                   ^
In file included from /home/titan/maskfusion/deps/toml11/toml.hpp:39:0,
                 from /home/titan/maskfusion/GUI/MainController.cpp:32:
/home/titan/maskfusion/deps/toml11/toml/get.hpp:75:1: note: candidate: template<class T, class C, template<class ...> class M, template<class ...> class V> toml::detail::enable_if_t<toml::detail::conjunction<toml::detail::is_basic_value<T>, toml::detail::negation<std::is_same<T, toml::basic_value<C, Tb, A> > > >::value, T> toml::get(const toml::basic_value<C, Tb, A>&)
 get(const basic_value<C, M, V>& v)
 ^
/home/titan/maskfusion/deps/toml11/toml/get.hpp:75:1: note:   template argument deduction/substitution failed:
/home/titan/maskfusion/GUI/MainController.cpp:278:83: error: template argument 1 is invalid
         const auto tomlMaskRCNN = toml::get<toml::Table>(tomlConfig.at("MaskRCNN"));
                                                                                   ^
In file included from /home/titan/maskfusion/deps/toml11/toml.hpp:39:0,
                 from /home/titan/maskfusion/GUI/MainController.cpp:32:
/home/titan/maskfusion/deps/toml11/toml/get.hpp:91:1: note: candidate: template<class T, class C, template<class ...> class M, template<class ...> class V> toml::detail::enable_if_t<toml::detail::conjunction<std::is_integral<_Tp>, toml::detail::negation<std::is_same<T, bool> >, toml::detail::negation<toml::detail::is_exact_toml_type<T, toml::basic_value<C, Tb, A> > > >::value, T> toml::get(const toml::basic_value<C, Tb, A>&)
 get(const basic_value<C, M, V>& v)
 ^
/home/titan/maskfusion/deps/toml11/toml/get.hpp:91:1: note:   template argument deduction/substitution failed:
/home/titan/maskfusion/GUI/MainController.cpp:278:83: error: template argument 1 is invalid
         const auto tomlMaskRCNN = toml::get<toml::Table>(tomlConfig.at("MaskRCNN"));
                                                                                   ^
In file included from /home/titan/maskfusion/deps/toml11/toml.hpp:39:0,
                 from /home/titan/maskfusion/GUI/MainController.cpp:32:
/home/titan/maskfusion/deps/toml11/toml/get.hpp:106:1: note: candidate: template<class T, class C, template<class ...> class M, template<class ...> class V> toml::detail::enable_if_t<toml::detail::conjunction<std::is_floating_point<_Tp>, toml::detail::negation<toml::detail::is_exact_toml_type<T, toml::basic_value<C, Tb, A> > > >::value, T> toml::get(const toml::basic_value<C, Tb, A>&)
 get(const basic_value<C, M, V>& v)
 ^
/home/titan/maskfusion/deps/toml11/toml/get.hpp:106:1: note:   template argument deduction/substitution failed:
/home/titan/maskfusion/GUI/MainController.cpp:278:83: error: template argument 1 is invalid
         const auto tomlMaskRCNN = toml::get<toml::Table>(tomlConfig.at("MaskRCNN"));
                                                                                   ^
In file included from /home/titan/maskfusion/deps/toml11/toml.hpp:39:0,
                 from /home/titan/maskfusion/GUI/MainController.cpp:32:
/home/titan/maskfusion/deps/toml11/toml/get.hpp:118:1: note: candidate: template<class T, class C, template<class ...> class M, template<class ...> class V> toml::detail::enable_if_t<std::is_same<T, std::__cxx11::basic_string<char> >::value, std::__cxx11::basic_string<char> >& toml::get(toml::basic_value<C, Tb, A>&)
 get(basic_value<C, M, V>& v)
 ^
/home/titan/maskfusion/deps/toml11/toml/get.hpp:118:1: note:   template argument deduction/substitution failed:
/home/titan/maskfusion/GUI/MainController.cpp:278:83: error: template argument 1 is invalid
         const auto tomlMaskRCNN = toml::get<toml::Table>(tomlConfig.at("MaskRCNN"));
                                                                                   ^
In file included from /home/titan/maskfusion/deps/toml11/toml.hpp:39:0,
                 from /home/titan/maskfusion/GUI/MainController.cpp:32:
/home/titan/maskfusion/deps/toml11/toml/get.hpp:126:1: note: candidate: template<class T, class C, template<class ...> class M, template<class ...> class V> toml::detail::enable_if_t<std::is_same<T, std::__cxx11::basic_string<char> >::value, std::__cxx11::basic_string<char> >& toml::get(const toml::basic_value<C, Tb, A>&)
 get(const basic_value<C, M, V>& v)
 ^
/home/titan/maskfusion/deps/toml11/toml/get.hpp:126:1: note:   template argument deduction/substitution failed:
/home/titan/maskfusion/GUI/MainController.cpp:278:83: error: template argument 1 is invalid
         const auto tomlMaskRCNN = toml::get<toml::Table>(tomlConfig.at("MaskRCNN"));
                                                                                   ^
In file included from /home/titan/maskfusion/deps/toml11/toml.hpp:39:0,
                 from /home/titan/maskfusion/GUI/MainController.cpp:32:
/home/titan/maskfusion/deps/toml11/toml/get.hpp:134:1: note: candidate: template<class T, class C, template<class ...> class M, template<class ...> class V> toml::detail::enable_if_t<std::is_same<T, std::__cxx11::basic_string<char> >::value, std::__cxx11::basic_string<char> >& toml::get(toml::basic_value<C, Tb, A>&&)
 get(basic_value<C, M, V>&& v)
 ^
/home/titan/maskfusion/deps/toml11/toml/get.hpp:134:1: note:   template argument deduction/substitution failed:
/home/titan/maskfusion/GUI/MainController.cpp:278:83: error: template argument 1 is invalid
         const auto tomlMaskRCNN = toml::get<toml::Table>(tomlConfig.at("MaskRCNN"));
                                                                                   ^
In file included from /home/titan/maskfusion/deps/toml11/toml.hpp:39:0,
                 from /home/titan/maskfusion/GUI/MainController.cpp:32:
/home/titan/maskfusion/deps/toml11/toml/get.hpp:158:1: note: candidate: template<class T, class C, template<class ...> class M, template<class ...> class V> toml::detail::enable_if_t<toml::detail::is_chrono_duration<T>::value, T> toml::get(const toml::basic_value<C, Tb, A>&)
 get(const basic_value<C, M, V>& v)
 ^
/home/titan/maskfusion/deps/toml11/toml/get.hpp:158:1: note:   template argument deduction/substitution failed:
/home/titan/maskfusion/GUI/MainController.cpp:278:83: error: template argument 1 is invalid
         const auto tomlMaskRCNN = toml::get<toml::Table>(tomlConfig.at("MaskRCNN"));
                                                                                   ^
In file included from /home/titan/maskfusion/deps/toml11/toml.hpp:39:0,
                 from /home/titan/maskfusion/GUI/MainController.cpp:32:
/home/titan/maskfusion/deps/toml11/toml/get.hpp:171:1: note: candidate: template<class T, class C, template<class ...> class M, template<class ...> class V> toml::detail::enable_if_t<std::is_same<std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > >, T>::value, T> toml::get(const toml::basic_value<C, Tb, A>&)
 get(const basic_value<C, M, V>& v)
 ^
/home/titan/maskfusion/deps/toml11/toml/get.hpp:171:1: note:   template argument deduction/substitution failed:
/home/titan/maskfusion/GUI/MainController.cpp:278:83: error: template argument 1 is invalid
         const auto tomlMaskRCNN = toml::get<toml::Table>(tomlConfig.at("MaskRCNN"));
                                                                                   ^
In file included from /home/titan/maskfusion/deps/toml11/toml.hpp:39:0,
                 from /home/titan/maskfusion/GUI/MainController.cpp:32:
/home/titan/maskfusion/deps/toml11/toml/get.hpp:276:1: note: candidate: template<class T, class C, template<class ...> class M, template<class ...> class V> toml::detail::enable_if_t<toml::detail::conjunction<toml::detail::is_container<T>, toml::detail::has_resize_method<T>, toml::detail::negation<toml::detail::is_exact_toml_type<T, toml::basic_value<C, Tb, A> > > >::value, T> toml::get(const toml::basic_value<C, Tb, A>&)
 get(const basic_value<C, M, V>& v)
 ^
/home/titan/maskfusion/deps/toml11/toml/get.hpp:276:1: note:   template argument deduction/substitution failed:
/home/titan/maskfusion/GUI/MainController.cpp:278:83: error: template argument 1 is invalid
         const auto tomlMaskRCNN = toml::get<toml::Table>(tomlConfig.at("MaskRCNN"));
                                                                                   ^
In file included from /home/titan/maskfusion/deps/toml11/toml.hpp:39:0,
                 from /home/titan/maskfusion/GUI/MainController.cpp:32:
/home/titan/maskfusion/deps/toml11/toml/get.hpp:298:1: note: candidate: template<class T, class C, template<class ...> class M, template<class ...> class V> toml::detail::enable_if_t<toml::detail::conjunction<toml::detail::is_container<T>, toml::detail::negation<toml::detail::has_resize_method<T> >, toml::detail::negation<toml::detail::is_exact_toml_type<T, toml::basic_value<C, Tb, A> > > >::value, T> toml::get(const toml::basic_value<C, Tb, A>&)
 get(const basic_value<C, M, V>& v)
 ^
/home/titan/maskfusion/deps/toml11/toml/get.hpp:298:1: note:   template argument deduction/substitution failed:
/home/titan/maskfusion/GUI/MainController.cpp:278:83: error: template argument 1 is invalid
         const auto tomlMaskRCNN = toml::get<toml::Table>(tomlConfig.at("MaskRCNN"));
                                                                                   ^
In file included from /home/titan/maskfusion/deps/toml11/toml.hpp:39:0,
                 from /home/titan/maskfusion/GUI/MainController.cpp:32:
/home/titan/maskfusion/deps/toml11/toml/get.hpp:323:1: note: candidate: template<class T, class C, template<class ...> class M, template<class ...> class V> toml::detail::enable_if_t<toml::detail::is_std_pair<T>::value, T> toml::get(const toml::basic_value<C, Tb, A>&)
 get(const basic_value<C, M, V>& v)
 ^
/home/titan/maskfusion/deps/toml11/toml/get.hpp:323:1: note:   template argument deduction/substitution failed:
/home/titan/maskfusion/GUI/MainController.cpp:278:83: error: template argument 1 is invalid
         const auto tomlMaskRCNN = toml::get<toml::Table>(tomlConfig.at("MaskRCNN"));
                                                                                   ^
In file included from /home/titan/maskfusion/deps/toml11/toml.hpp:39:0,
                 from /home/titan/maskfusion/GUI/MainController.cpp:32:
/home/titan/maskfusion/deps/toml11/toml/get.hpp:357:1: note: candidate: template<class T, class C, template<class ...> class M, template<class ...> class V> toml::detail::enable_if_t<toml::detail::is_std_tuple<T>::value, T> toml::get(const toml::basic_value<C, Tb, A>&)
 get(const basic_value<C, M, V>& v)
 ^
/home/titan/maskfusion/deps/toml11/toml/get.hpp:357:1: note:   template argument deduction/substitution failed:
/home/titan/maskfusion/GUI/MainController.cpp:278:83: error: template argument 1 is invalid
         const auto tomlMaskRCNN = toml::get<toml::Table>(tomlConfig.at("MaskRCNN"));
                                                                                   ^
In file included from /home/titan/maskfusion/deps/toml11/toml.hpp:39:0,
                 from /home/titan/maskfusion/GUI/MainController.cpp:32:
/home/titan/maskfusion/deps/toml11/toml/get.hpp:383:1: note: candidate: template<class T, class C, template<class ...> class M, template<class ...> class V> toml::detail::enable_if_t<toml::detail::conjunction<toml::detail::is_map<T>, toml::detail::negation<toml::detail::is_exact_toml_type<T, toml::basic_value<C, Tb, A> > > >::value, T> toml::get(const toml::basic_value<C, Tb, A>&)
 get(const basic_value<C, M, V>& v)
 ^
/home/titan/maskfusion/deps/toml11/toml/get.hpp:383:1: note:   template argument deduction/substitution failed:
/home/titan/maskfusion/GUI/MainController.cpp:278:83: error: template argument 1 is invalid
         const auto tomlMaskRCNN = toml::get<toml::Table>(tomlConfig.at("MaskRCNN"));
                                                                                   ^
In file included from /home/titan/maskfusion/deps/toml11/toml.hpp:39:0,
                 from /home/titan/maskfusion/GUI/MainController.cpp:32:
/home/titan/maskfusion/deps/toml11/toml/get.hpp:409:1: note: candidate: template<class T, class C, template<class ...> class M, template<class ...> class V> toml::detail::enable_if_t<toml::detail::conjunction<toml::detail::negation<toml::detail::is_exact_toml_type<T, toml::basic_value<C, Tb, A> > >, toml::detail::has_from_toml_method<T, C, M, V>, std::is_default_constructible<_Tp> >::value, T> toml::get(const toml::basic_value<C, Tb, A>&)
 get(const basic_value<C, M, V>& v)
 ^
/home/titan/maskfusion/deps/toml11/toml/get.hpp:409:1: note:   template argument deduction/substitution failed:
/home/titan/maskfusion/GUI/MainController.cpp:278:83: error: template argument 1 is invalid
         const auto tomlMaskRCNN = toml::get<toml::Table>(tomlConfig.at("MaskRCNN"));
                                                                                   ^
In file included from /home/titan/maskfusion/deps/toml11/toml.hpp:39:0,
                 from /home/titan/maskfusion/GUI/MainController.cpp:32:
/home/titan/maskfusion/deps/toml11/toml/get.hpp:418:3: note: candidate: template<class T, class C, template<class ...> class M, template<class ...> class V, long unsigned int S> T toml::get(const toml::basic_value<C, Tb, A>&)
 T get(const basic_value<C, M, V>& v)
   ^
/home/titan/maskfusion/deps/toml11/toml/get.hpp:418:3: note:   template argument deduction/substitution failed:
/home/titan/maskfusion/GUI/MainController.cpp:278:83: error: template argument 1 is invalid
         const auto tomlMaskRCNN = toml::get<toml::Table>(tomlConfig.at("MaskRCNN"));
                                                                                   ^
GUI/CMakeFiles/MaskFusion.dir/build.make:86: recipe for target 'GUI/CMakeFiles/MaskFusion.dir/MainController.cpp.o' failed
make[2]: *** [GUI/CMakeFiles/MaskFusion.dir/MainController.cpp.o] Error 1
CMakeFiles/Makefile2:211: recipe for target 'GUI/CMakeFiles/MaskFusion.dir/all' failed
make[1]: *** [GUI/CMakeFiles/MaskFusion.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

I git the latest toml at https://github.com/ToruNiina/toml11, is it because of the wrong version of toml or something else?

Best Wishes!

**Comment by wolf943134497** [comment]
hi  @robustlucy    How did you solve the problem?   I  encountered the problem. 
[ 89%] Building CXX object GUI/CMakeFiles/MaskFusion.dir/Tools/OpenNI2LiveReader.cpp.o
[ 91%] Building CXX object GUI/CMakeFiles/MaskFusion.dir/Tools/OpenNI2Interface.cpp.o
[ 93%] Building CXX object GUI/CMakeFiles/MaskFusion.dir/Tools/KlgLogReader.cpp.o
[ 95%] Building CXX object GUI/CMakeFiles/MaskFusion.dir/Tools/PangolinReader.cpp.o
[ 97%] Building CXX object GUI/CMakeFiles/MaskFusion.dir/Tools/FreenectLiveReader.cpp.o
/home/maskfusion/GUI/MainController.cpp:32:20: fatal error: toml.hpp: No such file or directory
compilation terminated.
GUI/CMakeFiles/MaskFusion.dir/build.make:86: recipe for target 'GUI/CMakeFiles/MaskFusion.dir/MainController.cpp.o' failed
make[2]: *** [GUI/CMakeFiles/MaskFusion.dir/MainController.cpp.o] Error 1
Can you tell me how to use toml? thanks! 
Best Wishes!
