### ISSUE TITLE
/home/sheng/maskfusion-master/Core/Segmentation/Slic.h:26:20: fatal error: gSLICr.h: No such file or 

### ISSUE THREAD

**Issue by shengrongjin** [martinruenz/maskfusion#3]
In file included from /home/sheng/maskfusion-master/Core/Segmentation/Segmentation.h:21:0,
                 from /home/sheng/maskfusion-master/Core/MaskFusion.h:38,
                 from /home/sheng/maskfusion-master/Core/MaskFusion.cpp:19:
/home/sheng/maskfusion-master/Core/Segmentation/Slic.h:26:20: fatal error: gSLICr.h: No such file or directory
 #include <gSLICr.h>
                    ^
compilation terminated.
Core/CMakeFiles/libmaskfusion.dir/build.make:155: recipe for target 'Core/CMakeFiles/libmaskfusion.dir/MaskFusion.cpp.o' failed
make[2]: *** [Core/CMakeFiles/libmaskfusion.dir/MaskFusion.cpp.o] Error 1
CMakeFiles/Makefile2:117: recipe for target 'Core/CMakeFiles/libmaskfusion.dir/all' failed
make[1]: *** [Core/CMakeFiles/libmaskfusion.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jiahaozebra** [comment]
找不到这个头文件，在你的当前目录中CMakeLists.txt添加
                   `target_include_directories(${PROJECT_NAME} PUBLIC
                            "/usr/include/gSLICr_Lib"          
)`

**Comment by NicksonYap** [comment]
Hi, @shengrongjin 

I see you have submitted a number of issues regarding compilation
Have you successfully compiled it, and whether this repo actually runs?

Thanks

**Comment by shengrongjin** [comment]
> 找不到这个头文件，在你的当前目录中CMakeLists.txt添加
> `target_include_directories(${PROJECT_NAME} PUBLIC "/usr/include/gSLICr_Lib" )`

Thank you for your help . Now I have meet a new problem that when I execute  make -j8 ../Utils/BoundingBox.h:31:41: error: no matching function for call to ‘BoundingBox::BoundingBox(<brace-enclosed initializer list>)’ 
 I don't know haw the error was caused . Can you have also meet this error ?

**Comment by shengrongjin** [comment]
> Hi, @shengrongjin
> 
> I see you have submitted a number of issues regarding compilation
> Have you successfully compiled it, and whether this repo actually runs?
> 
> Thanks

I have meet some problem when I build the project . Now I haven't success completely. My QQ is 934857682 , welcome you to have a communication with me !  Thank you .

**Comment by martinruenz** [comment]
This issue is fixed right (otherwise I'll re-open)? Was the issue that the dependency **gSLICr** was missing?

**Comment by shengrongjin** [comment]
> This issue is fixed right (otherwise I'll re-open)? Was the issue that the dependency **gSLICr** was missing?

Yes, thank you very much .

**Comment by shengrongjin** [comment]
@martinruenz  Yes, thank you very much .
