### ISSUE TITLE
How to run on a power 86 graphics card

### ISSUE THREAD

**Issue by BloodLemonS** [martinruenz/maskfusion#46]
What should I do if THE following error occurs when I make：
nvcc fatal   : Unsupported gpu architecture 'compute_86'
CMake Error at cuda_compile_1_generated_reduce.cu.o.cmake:219 (message):
  Error generating
  /home/lemons/maskfusion/build/Core/CMakeFiles/cuda_compile_1.dir/Cuda/./cuda_compile_1_generated_reduce.cu.o

nvcc fatal   : Unsupported gpu architecture 'compute_86'
CMake Error at cuda_compile_1_generated_segmentation.cu.o.cmake:219 (message):
  Error generating
  /home/lemons/maskfusion/build/Core/CMakeFiles/cuda_compile_1.dir/Cuda/./cuda_compile_1_generated_segmentation.cu.o

**Comment by andersonhusky** [comment]
hello, have you solved this problem?
