### ISSUE TITLE
I had meet the error that "error :no matching function for call to ‘BoundingBox::BoundingBox(<brace-enclosed initializer list>)’

### ISSUE THREAD

**Issue by shengrongjin** [martinruenz/maskfusion#5]
When I execute the last make step of  ''make -j8'' , I had meet the error that /home/sheng/maskfusion-master/Core/Segmentation/../Utils/BoundingBox.h:46:50: error: no matching function for call to ‘BoundingBox::BoundingBox(<brace-enclosed initializer list>)’
...........
...........
...........
[ 46%] Building CXX object Core/CMakeFiles/libmaskfusion.dir/Utils/Gnuplot.cpp.o
[ 48%] Building CXX object Core/CMakeFiles/libmaskfusion.dir/Utils/Parse.cpp.o
[ 51%] Building CXX object Core/CMakeFiles/libmaskfusion.dir/Utils/RGBDOdometry.cpp.o
[ 53%] Building CXX object Core/CMakeFiles/libmaskfusion.dir/Shaders/ComputePack.cpp.o
Core/CMakeFiles/libmaskfusion.dir/build.make:155: recipe for target 'Core/CMakeFiles/libmaskfusion.dir/MaskFusion.cpp.o' failed
make[2]: *** [Core/CMakeFiles/libmaskfusion.dir/MaskFusion.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:117: recipe for target 'Core/CMakeFiles/libmaskfusion.dir/all' failed
make[1]: *** [Core/CMakeFiles/libmaskfusion.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

How can I solve it and have a  correct build ?
Thank you for your enthusiastic answer !

**Comment by shengrongjin** [comment]
/home/sheng/maskfusion/Core/Segmentation/../Utils/BoundingBox.h: In member function ‘bool BoundingBox::includesLeftTopWidthHeight(int, int, int, int) const’:
/home/sheng/maskfusion/Core/Segmentation/../Utils/BoundingBox.h:46:50: error: no matching function for call to ‘BoundingBox::BoundingBox(<brace-enclosed initializer list>)’
         return includes(BoundingBox({t,l+w,t+h,l}));

/home/sheng/maskfusion/Core/Segmentation/../Utils/BoundingBox.h:55:102: error: no matching function for call to ‘BoundingBox::BoundingBox(<brace-enclosed initializer list>)’
         return BoundingBox({top-border_size, right+border_size, bottom+border_size, left-border_size});
                                                                                                      ^

**Comment by martinruenz** [comment]
I remember seeing this at some point due to an old gcc version. There are two fixes:
1) Update GCC
2) Replace the initializer list with a new suitable constructor (super easy to do)

I will probably implement 2 when I have a bit of spare time, alternatively a pull request would be welcome.

**Comment by shengrongjin** [comment]
@martinruenz Yes . Just as what you said , I have solved this problem by add a constructor. Thank you very much .

**Comment by bloo-cp** [comment]
excuse me,i have this problem too,could you share how to solve this problem?

**Comment by bloo-cp** [comment]
@shengrongjin
